### PR TITLE
fix(teams): called endpoints that exist on github enterprise

### LINKED ISSUE #235: Cannot manage teams: 404 not found
## Problem Description

Trying to manage teams via `settings.yml` results in an error.

### What is actually happening

Adding a team that isn't already in the teams page, e.g.

```yaml
teams:
  - name: ghe-admins
    permission: admin
```

Delivery of the event fails:

Screen Shot 2020-05-13 at 4 34 23 pm

### What is the expected behavior

The team is added to the repository.

### Error output, if available

```
{
  "name": "github",
  "hostname": "ad4f9a1b2614",
  "pid": 59,
  "installation": "21",
  "level": 20,
  "params": {
    "baseUrl": "https://github.example.com/api/v3",
    "mediaType": {
      "format": "",
      "previews": []
    },
    "request": {
      "validate": {
        "org": {
          "required": true,
          "type": "string"
        },
        "owner": {
          "required": true,
          "type": "string"
        },
        "repo": {
          "required": true,
          "type": "string"
        },
        "team_slug": {
          "required": true,
          "type": "string"
        }
      },
      "retryCount": 1
    },
    "team_slug": "ghe-admins",
    "owner": "MyOrg",
    "repo": "example-repo",
    "branch": "master",
    "required_pull_request_reviews": {
      "required_approving_review_count": 1,
      "dismiss_stale_reviews": true,
      "require_code_owner_reviews": true,
      "dismissal_restrictions": {}
    },
    "required_status_checks": {
      "strict": false,
      "contexts": []
    },
    "enforce_admins": false,
    "restrictions": null,
    "org": "MyOrg"
  },
  "msg": "GitHub request: DELETE /orgs/:org/teams/:team_slug/repos/:owner/:repo - 404",
  "time": "2020-05-13T06:16:08.283Z",
  "v": 0
}
```

### Are you using the hosted instance of probot/settings or running your own?

Own instance of probot/settings.

### If running your own instance, are you using it with github.com or GitHub Enterprise?

GitHub Enterprise

#### Version of probot/settings

Even with master as of today, i.e. https://github.com/probot/settings/tree/84a158a20c7ea9d19785bf0c655cbc689370aeea

#### Version of GitHub Enterprise

2.19.3

#### App Permissions

app-permissions

### PR DESCRIPTION
**Pull request by travi**
since the modern endpoints for .com dont exist on versions of ghe that are not yet EOL

fixes #235

### CODE REVIEW

File: lib/plugins/teams.js [hunk 1]
```diff
@@ -14,20 +18,28 @@ module.exports = class Teams extends Diffable {
...
   update (existing, attrs) {
-    return this.github.teams.addOrUpdateRepoInOrg(this.toParams(attrs))
+    return this.github.request(`PUT ${teamRepoEndpoint}`, this.toParams(existing, attrs))
   }
 
-  add (attrs) {
-    return this.github.teams.addOrUpdateRepoInOrg(this.toParams(attrs))
+  async add (attrs) {
+    const { data: existing } = await this.github.request(
+      'GET /orgs/:org/teams/:team_slug',
```
Comment (travi) [inline lib/plugins/teams.js:26]: dawned on me that this one isn't available either. i'll need to get this info in another way before this is ready

Comment (travi) [reply lib/plugins/teams.js:26]: actually, scratch that. looks like it is there, even in the now discontinued v2.17: https://developer.github.com/enterprise/2.17/v3/teams/#get-team-by-name
